"""superset group columns

v0.5.0 superseries: columna nullable superset_group en routine_exercises Y
workout_exercises (una única migración para ambos lados, mismo patrón que
rest_seconds tuvo en cada tabla). NULL = ejercicio suelto — todas las filas
existentes quedan NULL, sin backfill: antes de esta feature no había grupos.

Revision ID: 1162ad243925
Revises: fbf6cb158a4e
Create Date: 2026-08-07 14:46:10.699744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1162ad243925'
down_revision: Union[str, Sequence[str], None] = 'fbf6cb158a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('superset_group', sa.Integer(), nullable=True))

    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('superset_group', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_column('superset_group')

    with op.batch_alter_table('routine_exercises', schema=None) as batch_op:
        batch_op.drop_column('superset_group')

    # ### end Alembic commands ###
