"""workout exercise rest seconds

Revision ID: 3ef11d1b0db2
Revises: 55d9b0947067

NOTA para quien mergee este lane: down_revision apunta a 55d9b0947067 (mi
propia última migración en ESTE worktree, item 8 de esta misma ronda). Otro
lane paralelo puede llegar con su propia cabeza (p.ej. el color de usuario,
373083857bd5, ya en main pero no en este worktree); si al mergear alembic se
queja de heads múltiples, hace falta una migración de merge (`alembic merge
heads`) — no reescribir esta down_revision a mano.

Create Date: 2026-08-06 22:39:47.363631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef11d1b0db2'
down_revision: Union[str, Sequence[str], None] = '55d9b0947067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rest_seconds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_column('rest_seconds')

    # ### end Alembic commands ###
