"""workout stretched flag

Revision ID: 55d9b0947067
Revises: ed3204764c23
Create Date: 2026-08-06 22:25:16.455765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55d9b0947067'
down_revision: Union[str, Sequence[str], None] = 'ed3204764c23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default a mano (el autogenerate no lo pone): NOT NULL sobre una
    # tabla con filas existentes exige un valor de relleno para esas filas —
    # sin él, SQLite falla al recrear la tabla en modo batch. Se conserva
    # también tras el ADD COLUMN (no se retira con un alter_column aparte):
    # así cualquier INSERT futuro que no pase por el ORM también cae en False.
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('stretched', sa.Boolean(), nullable=False, server_default=sa.false())
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_column('stretched')

    # ### end Alembic commands ###
