"""catalog and sharing

Revision ID: 6069e3d62c58
Revises: db28a650ae63
Create Date: 2026-08-05 19:33:10.312949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6069e3d62c58'
down_revision: Union[str, Sequence[str], None] = 'db28a650ae63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_es', sa.String(length=80), nullable=False),
    sa.Column('name_en', sa.String(length=80), nullable=False),
    sa.Column('measurement', sa.String(length=10), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercises_owner_id'), ['owner_id'], unique=False)

    op.create_table('muscle_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=30), nullable=False),
    sa.Column('name_es', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('muscle_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_muscle_groups_owner_id'), ['owner_id'], unique=False)

    op.create_table('share_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('viewer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'viewer_id')
    )
    with op.batch_alter_table('share_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_grants_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_grants_viewer_id'), ['viewer_id'], unique=False)

    op.create_table('exercise_muscle_groups',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('muscle_group_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['muscle_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exercise_id', 'muscle_group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_muscle_groups')
    with op.batch_alter_table('share_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_grants_viewer_id'))
        batch_op.drop_index(batch_op.f('ix_share_grants_owner_id'))

    op.drop_table('share_grants')
    with op.batch_alter_table('muscle_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_muscle_groups_owner_id'))

    op.drop_table('muscle_groups')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercises_owner_id'))

    op.drop_table('exercises')
    # ### end Alembic commands ###
