"""workout exercise completed flag

v0.38.0 (zurdi: "check de marcar ejercicio como completado"): booleano NOT
NULL con server_default false, mismo patrón que workouts.stretched — las
filas existentes (entrenos pasados y el activo) nacen sin marcar, no hay
nada que rellenar hacia atrás.

Revision ID: 870485170758
Revises: c1d2e3f4a5b6
Create Date: 2026-08-24 21:19:54.633939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870485170758'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('completed', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
