"""single active workout index

Revision ID: ed3204764c23
Revises: 02cab11a3df6
Create Date: 2026-08-05 21:16:13.813507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed3204764c23'
down_revision: Union[str, Sequence[str], None] = '02cab11a3df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.create_index('ix_workouts_single_active', ['owner_id'], unique=True, sqlite_where=sa.text('ended_at IS NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_index('ix_workouts_single_active', sqlite_where=sa.text('ended_at IS NULL'))

    # ### end Alembic commands ###
